Theoretical Questions:

In [3]:
# 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does itenhance Python's capabilities for numerical operations?

NumPy (Numerical Python) is a foundational package for scientific computing and data analysis in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.
Advantages:
a powerful N - Dimensional array object
Sophisticated functions
Tools for intertgrating c/c++ and fortran code

In [ ]:
# 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over theother?

The np.mean() function calculates the arithmetic mean (simple average) of the elements in an array or along a specified axis.
The np.average() function computes the weighted average of the elements in an array or along a specified axis.

In [8]:
# 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [14]:
#for 1D
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1[::-1]

array([5, 4, 3, 2, 1])

In [16]:
#for 2D
arr2 = np.array([[1,2,4,5],[1,5,7,8],[1,6,7,4]])
arr2

array([[1, 2, 4, 5],
       [1, 5, 7, 8],
       [1, 6, 7, 4]])

In [18]:
#by row wise

In [26]:
arr2[::-1,:]

array([[1, 6, 7, 4],
       [1, 5, 7, 8],
       [1, 2, 4, 5]])

In [28]:
# by column wise

In [30]:
arr2[:,::-1]

array([[5, 4, 2, 1],
       [8, 7, 5, 1],
       [4, 7, 6, 1]])

In [37]:
# 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance

In [39]:
ar = np.array([1,2,3,4,5])
ar

array([1, 2, 3, 4, 5])

In [41]:
ar.dtype

dtype('int32')

memory allocation
Efficient use of cache
impact on data alignment
compution speed are the factors dtype in numpy

In [44]:
#5 .Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ndarray means n - dimensional array
Capability of the multidimensional array
containing homogenous data 
fixed size
efficient memory storage
broadcasting


In [48]:
#6 .Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

for large-scale numerical operations, NumPy arrays provide significant advantages in terms of memory efficiency, performance, and ease of use compared to Python lists. This makes NumPy the preferred choice for numerical computing in Python.

In [51]:
# 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Vstack is vertical stack for concatinacting array vertically
for 1d array output is 2d array along first axis = 0

In [56]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

out = np.vstack((arr1,arr2))
out

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

hstack is concacating to array as horizotaliy the 1d array as input to long 1d array as output, firts axis = 1

In [59]:
out = np.hstack((arr1,arr2),dtype = float)
out

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [61]:
import random

In [ ]:
# 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

fliplr >> used to flip 2d array horizontally means it reverse the order of the column left to right,axis = 1

In [71]:
arrr = np.random.randint(1,8,(3,3))
arrr

array([[4, 1, 3],
       [7, 4, 2],
       [4, 4, 5]])

In [75]:
np.fliplr(arrr)

array([[3, 1, 4],
       [2, 4, 7],
       [5, 4, 4]])

flipud>> used to flip the 2d array in vertically means reverse the order of row up to down,axis = 0 

In [80]:
arrr

array([[4, 1, 3],
       [7, 4, 2],
       [4, 4, 5]])

In [82]:
np.flipud(arrr)

array([[4, 4, 5],
       [7, 4, 2],
       [4, 1, 3]])

In [84]:
# 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [86]:
#used in split the array

arr  =  np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [94]:
np.array_split(arr,2)

[array([1, 2, 3]), array([4, 5])]

In [96]:
arr2 = np.random.randint(1,6,(3,3))
arr2

array([[1, 4, 5],
       [1, 5, 1],
       [4, 1, 4]])

In [98]:
np.array_split(arr2,3,axis = 1)

[array([[1],
        [1],
        [4]]),
 array([[4],
        [5],
        [1]]),
 array([[5],
        [1],
        [4]])]

In [100]:
# 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Pratical Questions?

In [107]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [109]:
arr = np.random.randint(1,100,(3,3))

In [111]:
arr

array([[23, 91, 35],
       [81,  3, 93],
       [12, 55,  9]])

In [113]:
#transpose
arr.T

array([[23, 81, 12],
       [91,  3, 55],
       [35, 93,  9]])

In [115]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [117]:
ar1  = np.array([1,2,3,4,5,6,7,8,9,10])
ar1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
ar1.reshape((5,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [123]:
ar1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [125]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [144]:
ar = np.random.rand(4,4)

In [146]:
ar

array([[0.55701742, 0.62806137, 0.54117818, 0.42176617],
       [0.98607102, 0.83687832, 0.4825165 , 0.92013097],
       [0.65349173, 0.6525173 , 0.06617422, 0.45056595],
       [0.8320509 , 0.5448343 , 0.32946052, 0.57207705]])

In [162]:
#using padding 

In [177]:
np.pad(ar,pad_width = 1 , mode = "constant",constant_values = 0)

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.55701742, 0.62806137, 0.54117818, 0.42176617,
        0.        ],
       [0.        , 0.98607102, 0.83687832, 0.4825165 , 0.92013097,
        0.        ],
       [0.        , 0.65349173, 0.6525173 , 0.06617422, 0.45056595,
        0.        ],
       [0.        , 0.8320509 , 0.5448343 , 0.32946052, 0.57207705,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

In [179]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [181]:
np.arange(10,60,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [183]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [185]:
arr = np.array(["python","numpy","pandas"])

In [187]:
arr.dtype

dtype('<U6')

In [195]:
np.char.upper(arr)

array(['PYTHON', 'NUMPY', 'PANDAS'], dtype='<U6')

In [199]:
np.char.lower(arr)

array(['python', 'numpy', 'pandas'], dtype='<U6')

In [201]:
np.char.title(arr)

array(['Python', 'Numpy', 'Pandas'], dtype='<U6')

In [203]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [9]:
import numpy as np
word = np.array(["hello","how","are","you"])

In [11]:
word

array(['hello', 'how', 'are', 'you'], dtype='<U5')

In [15]:
y = []

In [17]:
for i in x:
    y.append(" ".join(i))
y

['h e l l o', 'h o w', 'a r e', 'y o u']

In [19]:
spaced_array = np.array(y)

In [21]:
spaced_array

array(['h e l l o', 'h o w', 'a r e', 'y o u'], dtype='<U9')

In [ ]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [6]:
import numpy as np
import random

In [10]:
ar1 = np.random.randint(1,9,(3,3))
ar1

array([[5, 2, 1],
       [4, 6, 4],
       [7, 8, 1]])

In [12]:
ar2 = np.random.randint(1,6,(3,3))
ar2

array([[4, 1, 1],
       [2, 3, 5],
       [4, 5, 5]])

In [24]:
#addition
ar1+ar2 #or np.add(ar1,ar2)

array([[ 9,  3,  2],
       [ 6,  9,  9],
       [11, 13,  6]])

In [28]:
#substract
np.subtract(ar1,ar2)

array([[ 1,  1,  0],
       [ 2,  3, -1],
       [ 3,  3, -4]])

In [36]:
#multiplication
np.multiply(ar1,ar2) #ar1 * ar2

array([[20,  2,  1],
       [ 8, 18, 20],
       [28, 40,  5]])

In [40]:
#divide
np.divide(ar1,ar2)

array([[1.25, 2.  , 1.  ],
       [2.  , 2.  , 0.8 ],
       [1.75, 1.6 , 0.2 ]])

In [53]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [65]:
ident = np.eye(5,5,dtype = int)

In [67]:
ident

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [71]:
ident[[0,1,2,3,4],[0,1,2,3,4]]

array([1, 1, 1, 1, 1])

In [75]:
np.count_nonzero(ident)

5

In [77]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [110]:
arr = np.random.randint(0,1000,size = 100)

In [112]:
arr

array([771, 777, 513, 819, 383, 958,  16, 439,  20, 528, 491, 787, 324,
       632, 146, 651,   6, 639, 772, 369, 860, 178, 743, 333, 285, 349,
       333, 342, 348, 630, 201, 922, 379, 455, 793, 779,  72, 177, 703,
       452, 666, 244, 927, 731, 751, 815, 803, 125, 660, 782, 566, 273,
       843, 298, 995, 452, 118,  41,  25, 981, 945, 835, 360, 315, 702,
       272,  29, 354, 282, 378, 917, 779, 377, 387, 748,  97, 865, 883,
       702,  90, 247, 743, 748,  57, 554, 829, 736, 808, 635, 329, 183,
       165,  29, 460, 288, 422, 622, 218, 170, 846])

In [114]:
arr.size

100

In [130]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
        return True

prime_numbers = [n for n in arr if is_prime(n)]

In [134]:
print(prime_numbers,end = "")

[771, 777, 513, 819, 383, 439, 491, 787, 651, 639, 369, 743, 333, 285, 349, 333, 201, 379, 455, 793, 779, 177, 703, 927, 731, 751, 815, 803, 125, 273, 843, 995, 41, 25, 981, 945, 835, 315, 29, 917, 779, 377, 387, 97, 865, 883, 247, 743, 57, 829, 635, 329, 183, 165, 29]

In [136]:
#10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [165]:
daily_temp = np.random.randint(20,41,size = 28)
weekly_temp = daily_temp.reshape(4,7)
weekly_avg = np.mean(weekly_temp)
print("weeekly temperature = ",weekly_avg)


weeekly temperature =  31.464285714285715
